include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_expression_function_bodies: true
    flutter_style_todos: false
    require_trailing_commas: true
    public_member_api_docs: false
